#!/bin/bash

# [layout]
# |-- nvv <-- rename it to whatever you want & create a symlink to /usr/bin
# `-- nvim/
#     |-- init.lua
#     `-- lua/
#     |-- ...
#

NVIM_PROFILE_NAME=""
NVIM_INIT_FILE="init.lua"
NVIM_COMMAND="nvim"


SCRIPT_DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

ENV="XDG_CONFIG_HOME=$SCRIPT_DIR "
ENV+="XDG_CACHE_HOME=$SCRIPT_DIR/.cache "
ENV+="XDG_STATE_HOME=$SCRIPT_DIR/.local/state "
# ENV+="XDG_DATA_HOME='${SCRIPT_DIR}/.local/share' "
ENV+="XDG_DATA_HOME=$HOME/.local/share "

exec env $ENV $NVIM_COMMAND "$@"

